### ISSUE TITLE
the Data folder is missing

### ISSUE THREAD

**Issue by ntienvu** [aaronwtr/cfrnet-reproduction#1]
Hi all, thanks for sharing the code. 

Can you please share the Data folder for the ihdp1000 dataset ?
Without the Data folder, we may not be able to run the code. 

Thank you in advance,
Vu

**Comment by aaronwtr** [comment]
Hi,

Thanks for bringing this to our attention! This was done on purpose since the data are from large, publicly available sources. We have retrieved them through [here](https://www.fredjo.com/) under "Software & Data".  The data relevant for our code are the IHDP-1000 and Jobs datasets. 

I will also add this info in the Read Me file.

**Comment by ntienvu** [comment]
thank you! this is very helpful.
